# Generated by Django 3.2.16 on 2023-01-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230122_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='text',
            field=models.TextField(default='exit', max_length=250, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
