# Generated by Django 3.2.16 on 2023-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscriber_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriber',
            name='unique_user_following',
        ),
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.UniqueConstraint(fields=('user', 'subscriber'), name='unique_user_subscribing'),
        ),
    ]
